on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@1.0.0
        name: Verify formatting
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --check .
          version: v0.13.1
